---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: musicbox
  name: pvc-musicbox-file
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi
