apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: musicbox-app
  name: musicbox-app
  namespace: musicbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicbox-app
  template:
    metadata:
      labels:
        app: musicbox-app
    spec:
      containers:
        - name: musicbox-app
          image: registry.tino.sh/musicbox
          envFrom:
            - configMapRef:
                name: musicbox-config
          volumeMounts:
            - name: musicbox-file
              mountPath: /data
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "440Mi"
              cpu: "500m"
      volumes:
        - name: musicbox-file
          persistentVolumeClaim:
            claimName: pvc-musicbox-file
